%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/apprentice/Documents/MATLAB/Triage/OdysseyData11.xlsx
%    Worksheet: data
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/08/02 23:36:52

%% Import the data
[~, ~, raw] = xlsread('/Users/apprentice/Documents/MATLAB/Triage/OdysseyData12_Cough_Harm.xlsx','data');
raw = raw(2:1497,1:78);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78]);

%% Create table
HarmCoughData = table;

%% Allocate imported array to column variable names
HarmCoughData.case_no = cellfun(@num2str,cellVectors(:,1),'UniformOutput',false);
HarmCoughData.patient_no = cellVectors(:,2);
HarmCoughData.self_vs_dr = cellVectors(:,3);
HarmCoughData.tas_recommends = cellVectors(:,4);
HarmCoughData.pres_compl = cellVectors(:,5);
HarmCoughData.pc_chest = cellVectors(:,6);
HarmCoughData.pc_throat = cellVectors(:,7);
HarmCoughData.pc_abd = cellVectors(:,8);
HarmCoughData.pc_dig = cellVectors(:,9);
HarmCoughData.pc_ear = cellVectors(:,10);
HarmCoughData.pc_temp = cellVectors(:,11);
HarmCoughData.pc_skin = cellVectors(:,12);
HarmCoughData.pc_eye = cellVectors(:,13);
HarmCoughData.pc_head = cellVectors(:,14);
HarmCoughData.pc_nose = cellVectors(:,15);
HarmCoughData.pc_other = cellVectors(:,16);
HarmCoughData.ageband = cellVectors(:,17);
HarmCoughData.sex = cellVectors(:,18);
HarmCoughData.oldq1 = cellVectors(:,19);
HarmCoughData.questxt1 = cellVectors(:,20);
HarmCoughData.ans1 = cellVectors(:,21);
HarmCoughData.oldq2 = cellVectors(:,22);
HarmCoughData.questxt2 = cellVectors(:,23);
HarmCoughData.ans2 = cellVectors(:,24);
HarmCoughData.oldq3 = cellVectors(:,25);
HarmCoughData.questxt3 = cellVectors(:,26);
HarmCoughData.ans3 = cellVectors(:,27);
HarmCoughData.oldq4 = cellVectors(:,28);
HarmCoughData.questxt4 = cellVectors(:,29);
HarmCoughData.ans4 = cellVectors(:,30);
HarmCoughData.oldq5 = cellVectors(:,31);
HarmCoughData.questxt5 = cellVectors(:,32);
HarmCoughData.ans5 = cellVectors(:,33);
HarmCoughData.oldq6 = cellVectors(:,34);
HarmCoughData.questxt6 = cellVectors(:,35);
HarmCoughData.ans6 = cellVectors(:,36);
HarmCoughData.oldq7 = cellVectors(:,37);
HarmCoughData.questxt7 = cellVectors(:,38);
HarmCoughData.ans7 = cellVectors(:,39);
HarmCoughData.oldq8 = cellVectors(:,40);
HarmCoughData.questxt8 = cellVectors(:,41);
HarmCoughData.ans8 = cellVectors(:,42);
HarmCoughData.oldq9 = cellVectors(:,43);
HarmCoughData.questxt9 = cellVectors(:,44);
HarmCoughData.ans9 = cellVectors(:,45);
HarmCoughData.oldq10 = cellVectors(:,46);
HarmCoughData.questxt10 = cellVectors(:,47);
HarmCoughData.ans10 = cellVectors(:,48);
HarmCoughData.oldq11 = cellVectors(:,49);
HarmCoughData.questxt11 = cellVectors(:,50);
HarmCoughData.ans11 = cellVectors(:,51);
HarmCoughData.oldq12 = cellVectors(:,52);
HarmCoughData.questxt12 = cellVectors(:,53);
HarmCoughData.ans12 = cellVectors(:,54);
HarmCoughData.oldq13 = cellVectors(:,55);
HarmCoughData.questxt13 = cellVectors(:,56);
HarmCoughData.ans13 = cellVectors(:,57);
HarmCoughData.oldq14 = cellVectors(:,58);
HarmCoughData.questxt14 = cellVectors(:,59);
HarmCoughData.ans14 = cellVectors(:,60);
HarmCoughData.oldq15 = cellVectors(:,61);
HarmCoughData.questxt15 = cellVectors(:,62);
HarmCoughData.ans15 = cellVectors(:,63);
HarmCoughData.oldq16 = cellVectors(:,64);
HarmCoughData.questxt16 = cellVectors(:,65);
HarmCoughData.ans16 = cellVectors(:,66);
HarmCoughData.oldq17 = cellVectors(:,67);
HarmCoughData.questxt17 = cellVectors(:,68);
HarmCoughData.ans17 = cellVectors(:,69);
HarmCoughData.oldq18 = cellVectors(:,70);
HarmCoughData.questxt18 = cellVectors(:,71);
HarmCoughData.ans18 = cellVectors(:,72);
HarmCoughData.oldq19 = cellVectors(:,73);
HarmCoughData.questxt19 = cellVectors(:,74);
HarmCoughData.ans19 = cellVectors(:,75);
HarmCoughData.oldq20 = cellVectors(:,76);
HarmCoughData.questxt20 = cellVectors(:,77);
HarmCoughData.ans20 = cellVectors(:,78);

%% Clear temporary variables
clearvars data raw cellVectors;
