%% Import ChestData from spreadsheet
% Script for importing ChestData from the following spreadsheet:
%
%    Workbook: /Users/apprentice/Documents/MATLAB/Triage/OdysseyData12_Chest2.xlsx
%    Worksheet: ChestData
%
% To extend the code for use with different selected ChestData or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/08/02 23:36:52

%% Import the ChestData
[~, ~, raw] = xlsread('/Users/apprentice/Documents/MATLAB/Triage/OdysseyData12_Chest2.xlsx','data');
raw = raw(2:11187,1:78);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78]);

%% Create table
ChestData = table;

%% Allocate imported array to column variable names
ChestData.case_no = cellfun(@num2str,cellVectors(:,1),'UniformOutput',false);
ChestData.patient_no = cellVectors(:,2);
ChestData.self_vs_dr = cellVectors(:,3);
ChestData.tas_recommends = cellVectors(:,4);
ChestData.pres_compl = cellVectors(:,5);
ChestData.pc_chest = cellVectors(:,6);
ChestData.pc_cough = cellVectors(:,7);
ChestData.pc_breath = cellVectors(:,8);
ChestData.pc_chest2 = cellVectors(:,9);
ChestData.pc_asth = cellVectors(:,10);
ChestData.pc_wheez = cellVectors(:,11);
ChestData.pc_bronchi = cellVectors(:,12);
ChestData.pc_eye = cellVectors(:,13);
ChestData.pc_head = cellVectors(:,14);
ChestData.pc_nose = cellVectors(:,15);
ChestData.pc_other = cellVectors(:,16);
ChestData.ageband = cellVectors(:,17);
ChestData.sex = cellVectors(:,18);
ChestData.oldq1 = cellVectors(:,19);
ChestData.questxt1 = cellVectors(:,20);
ChestData.ans1 = cellVectors(:,21);
ChestData.oldq2 = cellVectors(:,22);
ChestData.questxt2 = cellVectors(:,23);
ChestData.ans2 = cellVectors(:,24);
ChestData.oldq3 = cellVectors(:,25);
ChestData.questxt3 = cellVectors(:,26);
ChestData.ans3 = cellVectors(:,27);
ChestData.oldq4 = cellVectors(:,28);
ChestData.questxt4 = cellVectors(:,29);
ChestData.ans4 = cellVectors(:,30);
ChestData.oldq5 = cellVectors(:,31);
ChestData.questxt5 = cellVectors(:,32);
ChestData.ans5 = cellVectors(:,33);
ChestData.oldq6 = cellVectors(:,34);
ChestData.questxt6 = cellVectors(:,35);
ChestData.ans6 = cellVectors(:,36);
ChestData.oldq7 = cellVectors(:,37);
ChestData.questxt7 = cellVectors(:,38);
ChestData.ans7 = cellVectors(:,39);
ChestData.oldq8 = cellVectors(:,40);
ChestData.questxt8 = cellVectors(:,41);
ChestData.ans8 = cellVectors(:,42);
ChestData.oldq9 = cellVectors(:,43);
ChestData.questxt9 = cellVectors(:,44);
ChestData.ans9 = cellVectors(:,45);
ChestData.oldq10 = cellVectors(:,46);
ChestData.questxt10 = cellVectors(:,47);
ChestData.ans10 = cellVectors(:,48);
ChestData.oldq11 = cellVectors(:,49);
ChestData.questxt11 = cellVectors(:,50);
ChestData.ans11 = cellVectors(:,51);
ChestData.oldq12 = cellVectors(:,52);
ChestData.questxt12 = cellVectors(:,53);
ChestData.ans12 = cellVectors(:,54);
ChestData.oldq13 = cellVectors(:,55);
ChestData.questxt13 = cellVectors(:,56);
ChestData.ans13 = cellVectors(:,57);
ChestData.oldq14 = cellVectors(:,58);
ChestData.questxt14 = cellVectors(:,59);
ChestData.ans14 = cellVectors(:,60);
ChestData.oldq15 = cellVectors(:,61);
ChestData.questxt15 = cellVectors(:,62);
ChestData.ans15 = cellVectors(:,63);
ChestData.oldq16 = cellVectors(:,64);
ChestData.questxt16 = cellVectors(:,65);
ChestData.ans16 = cellVectors(:,66);
ChestData.oldq17 = cellVectors(:,67);
ChestData.questxt17 = cellVectors(:,68);
ChestData.ans17 = cellVectors(:,69);
ChestData.oldq18 = cellVectors(:,70);
ChestData.questxt18 = cellVectors(:,71);
ChestData.ans18 = cellVectors(:,72);
ChestData.oldq19 = cellVectors(:,73);
ChestData.questxt19 = cellVectors(:,74);
ChestData.ans19 = cellVectors(:,75);
ChestData.oldq20 = cellVectors(:,76);
ChestData.questxt20 = cellVectors(:,77);
ChestData.ans20 = cellVectors(:,78);

%% Clear temporary variables
clearvars data raw cellVectors;
