%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/apprentice/Documents/MATLAB/Triage/OdysseyData11.xlsx
%    Worksheet: data
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/08/02 23:36:52

%% Import the data
[~, ~, raw] = xlsread('/Users/apprentice/Documents/MATLAB/Triage/OdysseyData12_Throat_Harm.xlsx','data');
raw = raw(2:3367,1:78);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78]);

%% Create table
HarmThroatData = table;

%% Allocate imported array to column variable names
HarmThroatData.case_no = cellfun(@num2str,cellVectors(:,1),'UniformOutput',false);
HarmThroatData.patient_no = cellVectors(:,2);
HarmThroatData.self_vs_dr = cellVectors(:,3);
HarmThroatData.tas_recommends = cellVectors(:,4);
HarmThroatData.pres_compl = cellVectors(:,5);
HarmThroatData.pc_chest = cellVectors(:,6);
HarmThroatData.pc_throat = cellVectors(:,7);
HarmThroatData.pc_abd = cellVectors(:,8);
HarmThroatData.pc_dig = cellVectors(:,9);
HarmThroatData.pc_ear = cellVectors(:,10);
HarmThroatData.pc_temp = cellVectors(:,11);
HarmThroatData.pc_skin = cellVectors(:,12);
HarmThroatData.pc_eye = cellVectors(:,13);
HarmThroatData.pc_head = cellVectors(:,14);
HarmThroatData.pc_nose = cellVectors(:,15);
HarmThroatData.pc_other = cellVectors(:,16);
HarmThroatData.ageband = cellVectors(:,17);
HarmThroatData.sex = cellVectors(:,18);
HarmThroatData.oldq1 = cellVectors(:,19);
HarmThroatData.questxt1 = cellVectors(:,20);
HarmThroatData.ans1 = cellVectors(:,21);
HarmThroatData.oldq2 = cellVectors(:,22);
HarmThroatData.questxt2 = cellVectors(:,23);
HarmThroatData.ans2 = cellVectors(:,24);
HarmThroatData.oldq3 = cellVectors(:,25);
HarmThroatData.questxt3 = cellVectors(:,26);
HarmThroatData.ans3 = cellVectors(:,27);
HarmThroatData.oldq4 = cellVectors(:,28);
HarmThroatData.questxt4 = cellVectors(:,29);
HarmThroatData.ans4 = cellVectors(:,30);
HarmThroatData.oldq5 = cellVectors(:,31);
HarmThroatData.questxt5 = cellVectors(:,32);
HarmThroatData.ans5 = cellVectors(:,33);
HarmThroatData.oldq6 = cellVectors(:,34);
HarmThroatData.questxt6 = cellVectors(:,35);
HarmThroatData.ans6 = cellVectors(:,36);
HarmThroatData.oldq7 = cellVectors(:,37);
HarmThroatData.questxt7 = cellVectors(:,38);
HarmThroatData.ans7 = cellVectors(:,39);
HarmThroatData.oldq8 = cellVectors(:,40);
HarmThroatData.questxt8 = cellVectors(:,41);
HarmThroatData.ans8 = cellVectors(:,42);
HarmThroatData.oldq9 = cellVectors(:,43);
HarmThroatData.questxt9 = cellVectors(:,44);
HarmThroatData.ans9 = cellVectors(:,45);
HarmThroatData.oldq10 = cellVectors(:,46);
HarmThroatData.questxt10 = cellVectors(:,47);
HarmThroatData.ans10 = cellVectors(:,48);
HarmThroatData.oldq11 = cellVectors(:,49);
HarmThroatData.questxt11 = cellVectors(:,50);
HarmThroatData.ans11 = cellVectors(:,51);
HarmThroatData.oldq12 = cellVectors(:,52);
HarmThroatData.questxt12 = cellVectors(:,53);
HarmThroatData.ans12 = cellVectors(:,54);
HarmThroatData.oldq13 = cellVectors(:,55);
HarmThroatData.questxt13 = cellVectors(:,56);
HarmThroatData.ans13 = cellVectors(:,57);
HarmThroatData.oldq14 = cellVectors(:,58);
HarmThroatData.questxt14 = cellVectors(:,59);
HarmThroatData.ans14 = cellVectors(:,60);
HarmThroatData.oldq15 = cellVectors(:,61);
HarmThroatData.questxt15 = cellVectors(:,62);
HarmThroatData.ans15 = cellVectors(:,63);
HarmThroatData.oldq16 = cellVectors(:,64);
HarmThroatData.questxt16 = cellVectors(:,65);
HarmThroatData.ans16 = cellVectors(:,66);
HarmThroatData.oldq17 = cellVectors(:,67);
HarmThroatData.questxt17 = cellVectors(:,68);
HarmThroatData.ans17 = cellVectors(:,69);
HarmThroatData.oldq18 = cellVectors(:,70);
HarmThroatData.questxt18 = cellVectors(:,71);
HarmThroatData.ans18 = cellVectors(:,72);
HarmThroatData.oldq19 = cellVectors(:,73);
HarmThroatData.questxt19 = cellVectors(:,74);
HarmThroatData.ans19 = cellVectors(:,75);
HarmThroatData.oldq20 = cellVectors(:,76);
HarmThroatData.questxt20 = cellVectors(:,77);
HarmThroatData.ans20 = cellVectors(:,78);

%% Clear temporary variables
clearvars data raw cellVectors;
